### ISSUE TITLE
Gnome Platform 3.32 is end-of-life

### ISSUE THREAD

**Issue by evenreven** [flathub/com.github.PintaProject.Pinta#7]
Message from flatpak cli:

`org.gnome.Platform is end-of-life, with reason: The GNOME 3.32 runtime is no longer supported as of 11th March 2020. Please ask your application developer to migrate to a supported platform.`

So this should probably be upgraded. Might as well go to 3.36 since it's out?

**Comment by scx** [comment]
> Message from flatpak cli:
> 
> `org.gnome.Platform is end-of-life, with reason: The GNOME 3.32 runtime is no longer supported as of 11th March 2020. Please ask your application developer to migrate to a supported platform.`
> 
> So this should probably be upgraded. Might as well go to 3.36 since it's out?

I've already wanted to do this several weeks ago, but the **Mono** extension (`org.freedesktop.Sdk.Extension.mono5`) is still not available on **Freedesktop** _19.08_ (`org.freedesktop.Platform//19.08`), on which **GNOME** _3.34_ (`org.gnome.Platform/x86_64/3.34`) & _3.36_ (`org.gnome.Platform/x86_64/3.36`) are based. We have been waiting for it since September 2019.
https://github.com/flathub/org.freedesktop.Sdk.Extension.mono5/issues/7#issuecomment-604959005

**Comment by scx** [comment]
@evenreven 

> Message from flatpak cli:
> 
> `org.gnome.Platform is end-of-life, with reason: The GNOME 3.32 runtime is no longer supported as of 11th March 2020. Please ask your application developer to migrate to a supported platform.`
> 
> So this should probably be upgraded. Might as well go to 3.36 since it's out?

I've already wanted to do this several weeks ago, but the **Mono** extension (`org.freedesktop.Sdk.Extension.mono5`) is still not available on **Freedesktop** _19.08_ (`org.freedesktop.Platform//19.08`), on which **GNOME** _3.34_ (`org.gnome.Platform//3.34`) & _3.36_ (`org.gnome.Platform//3.36`) are based. We have been waiting for it since September 2019.
https://github.com/flathub/org.freedesktop.Sdk.Extension.mono5/issues/7#issuecomment-604959005

**Comment by darkdragon-001** [comment]
This is fixed upstream by now. I would suggest migrating to mono v6 directly including complete Python3 support (#9).

**Comment by darkdragon-001** [comment]
Fixed in #8
